### ISSUE TITLE
Support for args on "configure_control" function

### ISSUE THREAD

**Issue by sennomau** [chaostoolkit/chaostoolkit-lib#143]
It would be useful to be able to pass arguments to the "configure_control" function to make it easier to customise its behaviour by configuring it in the "controls" section of the experiment json file. This would be similar to what we can do with "actions" and "probes" functions.

Example
```
controls:  
  - name: Check Helm chart artifactory 
    provider:
      type: python
      module: mypackage.controls.global_helm
      func: configure_control
        arguments:
          chart_file: xyz.tr.gz
          values_file: xyz_values.yaml
```
and the corresponding function signature
```
def configure_control(chart_file: str, values_file: str):
```
