### ISSUE TITLE
Load experiment configuration context from files even if not defined in experiment template

### ISSUE THREAD

**Issue by mcastellin** [chaostoolkit/chaostoolkit-lib#257]
**Is your feature request related to a problem? Please describe.**
When defining controls from file with *control-file* options like `chaosaws.s3.controls.upload` it's impossible to set the required configuration properties unless those properties are already part of the experiment template.
This can be impractical if you want a control to be transparent to the template.

I may want to use the `chaosaws.s3.controls.upload` to upload the journal into an S3 bucket but that doesn't mean the experiment is using AWS so I shouldn't be forced to add AWS parameters into every experiment.

**Describe the solution you'd like**
Should be able to set variables from files even if they're not defined in the experiment file.

**Describe alternatives you've considered**
Alternatively we could have an option in the **settings** and **control-file** files to specify control-specific configuration.

**Additional context**
Example:

experiment.yaml
```yaml
title: test
description: test

steady-state-hypothesis:
  title: "All container replicas should be online"
  probes:
    - type: probe
      name: "service-must-respond"
      tolerance: 200
      provider:
        type: http
        url: "http://localhost:8080"
        method: "GET"
        timeout: 5

method: []
```

upload-journal.yaml
```yaml
s3-upload:
  provider:
    type: python
    module: chaosaws.s3.controls.upload
    arguments:
      bucket_name: "experiment-journals"
      suffix_with_timestamp: true
      dirpath: 'journals'
```

local-configuration.yaml
```yaml
configuration:
  aws_profile_name: default
  aws_region: eu-west-1
```

Running the following command at the moment doesn't work as suggested:

```
chaos run --control-file upload-journal.yaml --var-file local-configuration.yaml experiment.yaml
```
